name: Bug Report
description: File a bug report for DynoLink
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible to help us fix the issue.

  - type: input
    id: version
    attributes:
      label: DynoLink version
      placeholder: e.g. 1.0.2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Run with this input '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context or logs
      placeholder: Paste error logs, screenshots, or related code snippets
