name: Feature Request
description: Suggest a new feature or improvement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: input
    id: version
    attributes:
      label: DynoLink version (if relevant)
      placeholder: e.g. 1.0.2

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      placeholder: Describe the feature or behavior you want
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature needed?
      placeholder: Tell us the problem this feature would solve

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you’ve considered
